Repository ros2/rcpputils, pull requests merged in 2020-06, with the labels that each got.

#67 Handle empty paths in is_absolute
  include/rcpputils/filesystem_helper.hpp
  test/test_filesystem_helper.cpp
Labels: bug, in review

#69 Include stdexcept in get_env.hpp
  include/rcpputils/get_env.hpp
Labels: bug

#68 Align path combine behavior with C++17
  include/rcpputils/filesystem_helper.hpp
  test/test_filesystem_helper.cpp
Labels: bug, in review

#63 Add current_path to filesystem_helpers
  CMakeLists.txt
  include/rcpputils/filesystem_helper.hpp
  test/test_filesystem_helper.cpp
Labels: enhancement

#72 Address memory leak in remove pointer test
  test/test_pointer_traits.cpp
Labels: bug

#70 Add get_executable_name() function
  CMakeLists.txt
  include/rcpputils/process.hpp
  test/test_process.cpp
Labels: enhancement, in review
